//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecFlow.Reporting.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecFlow.Reporting.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_eot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_svg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_ttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regular_woff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html ng-app=&quot;app&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;__TITLE__&lt;/title&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link href=&quot;styles.css?v=__VERSION__&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body ng-view&gt;
        ///
        ///    &lt;script src=&quot;scripts.js?v=__VERSION__&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;report.js?v=__VERSION__&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * SpecFlow.Reporting.WebApp v0.0.0 by Tim Schlechter
        /// * 
        /// */
        ///(function(global,factory){if(typeof module===&quot;object&quot;&amp;&amp;typeof module.exports===&quot;object&quot;){module.exports=global.document?factory(global,true):function(w){if(!w.document){throw new Error(&quot;jQuery requires a window with a document&quot;)}return factory(w)}}else{factory(global)}})(typeof window!==&quot;undefined&quot;?window:this,function(window,noGlobal){var arr=[];var slice=arr.slice;var concat=arr.concat;var push=arr.push;var indexOf=arr.indexOf;var class2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scripts {
            get {
                return ResourceManager.GetString("scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v3.0.0 | MIT License | git.io/normalize */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:1px dotted}b,strong{font-wei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular.module(&apos;app&apos;).run([&apos;$templateCache&apos;, function($templateCache) {
        ///  &apos;use strict&apos;;
        ///
        ///  $templateCache.put(&apos;views/dashboard.tpl.html&apos;,
        ///    &quot;&lt;div ng-if=\&quot;selectedScenario\&quot; class=\&quot;row\&quot; ng-controller=\&quot;DashboardController\&quot;&gt;&lt;div class=\&quot;col-md-3 sidebar\&quot;&gt;&lt;div class=\&quot;alert alert-info feature\&quot;&gt;&lt;h4&gt;Feature: {{selectedFeature.title}}&lt;/h4&gt;{{selectedFeature.description}}&lt;/div&gt;&lt;/div&gt;&lt;div class=\&quot;col-md-9\&quot;&gt;&lt;div class=\&quot;bs-docs-sidebar scenario-summary\&quot;&gt;&lt;h3&gt;Scenario: {{selectedScenario.title}}&lt;/h3&gt;&lt;ul cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
    }
}
